Repository ZhuoZhuoCrayon/throttled-py, pull requests merged in 2025-05, with the labels that each got.

#55 perf: optimize rate limiting algorithm performance
  tests/rate_limiter/test_gcra.py
  tests/rate_limiter/test_leaking_bucket.py
  tests/store/test_memory.py
  tests/store/test_store.py
  throttled/constants.py
  throttled/rate_limiter/base.py
  throttled/rate_limiter/fixed_window.py
  throttled/rate_limiter/gcra.py
  throttled/rate_limiter/leaking_bucket.py
  throttled/rate_limiter/sliding_window.py
  throttled/rate_limiter/token_bucket.py
  throttled/store/memory.py
Labels: kind/perf

#56 build: update package metadata
  pyproject.toml
  throttled/__init__.py
Labels: kind/build

#57 docs: update readme with pypi package link
  README.md
  README_ZH.md
Labels: kind/docs

#58 ci: update regex pattern for ci/skip-changelog
  .github/release-drafter-config.yml
  tests/rate_limiter/test_gcra.py
Labels: kind/ci

#60 docs: optimize quick start examples for low-configuration servers
  README.md
  README_ZH.md
  examples/basic/quickstart_example.py
  examples/basic/timeout_example.py
  throttled/utils.py
Labels: kind/docs

#61 docs: optimize README navigation
  README.md
  README_ZH.md
Labels: kind/docs

#62 build: update package metadata & readme navigation links
  README.md
  README_ZH.md
  pyproject.toml
Labels: kind/build

#63 docs: release v2.0.2
  CHANGELOG.md
  CHANGELOG_EN.md
  README.md
  pyproject.toml
  throttled/__init__.py
Labels: kind/docs, ci/skip-changelog

#64 docs: update README_ZH.md with English link
  README_ZH.md
Labels: kind/docs

#65 feat: add asyncio-based implementation for MemoryStore (issue #36)
  poetry.lock
  pyproject.toml
  tests/asyncio/__init__.py
  tests/asyncio/conftest.py
  tests/asyncio/store/__init__.py
  tests/asyncio/store/test_memory.py
  tests/asyncio/store/test_store.py
  tests/store/parametrizes.py
  tests/store/test_store.py
  throttled/__init__.py
  throttled/asyncio/__init__.py
  throttled/asyncio/store/__init__.py
  throttled/asyncio/store/base.py
  throttled/asyncio/store/memory.py
  throttled/asyncio/store/redis.py
  throttled/store/base.py
  throttled/store/memory.py
Labels: kind/feat

#66 feat: add asyncio-based implementation for RedisStore (issue #36)
  tests/asyncio/conftest.py
  throttled/asyncio/__init__.py
  throttled/asyncio/store/__init__.py
  throttled/asyncio/store/base.py
  throttled/asyncio/store/memory.py
  throttled/asyncio/store/redis.py
  throttled/store/base.py
  throttled/store/redis.py
  throttled/store/redis_pool.py
Labels: kind/feat

#68 refactor: simplify rate limiter and store backend implementations
  codecov.yml
  tests/test_utils.py
  throttled/asyncio/rate_limiter/base.py
  throttled/asyncio/rate_limiter/fixed_window.py
  throttled/asyncio/store/__init__.py
  throttled/asyncio/store/base.py
  throttled/asyncio/store/memory.py
  throttled/asyncio/store/redis.py
  throttled/rate_limiter/__init__.py
  throttled/rate_limiter/base.py
  throttled/rate_limiter/fixed_window.py
  throttled/rate_limiter/gcra.py
  throttled/rate_limiter/leaking_bucket.py
  throttled/rate_limiter/sliding_window.py
  throttled/rate_limiter/token_bucket.py
  throttled/store/base.py
  throttled/store/memory.py
  throttled/store/redis.py
  throttled/types.py
  throttled/utils.py
Labels: kind/refactor

#70 feat: implement "Sliding Window" Rate Limiter with async support (issue #36)
  tests/asyncio/rate_limiter/test_sliding_window.py
  tests/rate_limiter/test_sliding_window.py
  throttled/asyncio/rate_limiter/__init__.py
  throttled/asyncio/rate_limiter/sliding_window.py
  throttled/asyncio/store/base.py
  throttled/rate_limiter/leaking_bucket.py
  throttled/rate_limiter/lua/sliding_window.lua
  throttled/rate_limiter/sliding_window.py
  throttled/store/base.py
  throttled/types.py
Labels: kind/feat

#71 feat: implement "Token Bucket" Rate Limiter with async support (issue #36)
  tests/asyncio/rate_limiter/test_token_bucket.py
  tests/rate_limiter/test_token_bucket.py
  throttled/asyncio/rate_limiter/__init__.py
  throttled/asyncio/rate_limiter/token_bucket.py
  throttled/rate_limiter/leaking_bucket.py
  throttled/rate_limiter/token_bucket.py
Labels: kind/feat

#73 feat: add async support for Throttled (issue #36)
  tests/asyncio/benchmarks/__init__.py
  tests/asyncio/benchmarks/test_throttled.py
  tests/asyncio/conftest.py
  tests/asyncio/test_throttled.py
  tests/benchmarks/test_throttled.py
  tests/test_throttled.py
  throttled/asyncio/__init__.py
  throttled/asyncio/store/memory.py
  throttled/asyncio/store/redis.py
  throttled/asyncio/throttled.py
  throttled/constants.py
  throttled/store/memory.py
  throttled/store/redis.py
  throttled/store/redis_pool.py
  throttled/throttled.py
  throttled/types.py
  throttled/utils.py
Labels: kind/feat

#75 docs: release v2.1.0
  CHANGELOG.md
  CHANGELOG_EN.md
  README.md
  README_ZH.md
  pyproject.toml
  throttled/__init__.py
  throttled/asyncio/__init__.py
Labels: kind/docs, ci/skip-changelog

#76 docs: add HelloGitHub recommendation badge to README
  README.md
  README_ZH.md
Labels: kind/docs

#77 feat: enhance Throttled decorator with cost parameter and add examples for synchronous and asynchronous usage
  .gitignore
  examples/basic/decorator_example.py
  tests/asyncio/rate_limiter/test_sliding_window.py
  tests/rate_limiter/test_base.py
  throttled/asyncio/throttled.py
  throttled/store/base.py
  throttled/throttled.py
Labels: kind/feat

#78 docs: release v2.2.0
  CHANGELOG.md
  CHANGELOG_EN.md
  pyproject.toml
  throttled/__init__.py
  throttled/asyncio/__init__.py
Labels: kind/docs
